name: 每小时备份数据库

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull
        uses: actions/checkout@v3 # git pull

      - name: Get current date
        id: date
        run: echo "::set-output name=time::$(date +'%Y%m%d%H%M%S')"

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: bstu.cn
          username: root
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            echo ${{ steps.date.outputs.time }}
            docker exec mariadb sh -c 'mariadb-dump -uroot -p${{ secrets.SQL_PASSWORD }} bdm296810572_db' > /data/docker/mariadb/backup/bdm296810572_db/${{ steps.date.outputs.time }}.dump